config/routes.rb
ExpenseManager::Application.routes.draw do
  get "front/index"

  resources :posts
	resources :expenses
  match 'payments/new' => 'expenses#new'
  
	root :to => 'front#index'
  devise_for :users
  resources :users, :only => :show
	
	get "home/index"

end

app/views/shared/_footer.html.erb
<div class="container">
<p class="pull-right">
	<a href="#">Back to top</a>
</p>
<p class="muted">Developed By: Kashyap Bhatt</p>

<p class="pull-right">
	<a href="https://github.com/kashyap-bhatt15/expense_manager" target="_blank">Codebase</a>
</p>
<p class="muted">Graduate Student at FresnoState</p>
</div>

app/views/shared/_header.html.erb
<div class="navbar-wrapper">
<div class="container">
<div class="navbar navbar-inverse">
 	<div class="navbar-inner">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand" href="/">ExpenseManager</a>
	      <div class="nav-collapse collapse">
	        <ul class="nav">
        		<% if (params[:controller] == 'home' && params[:action] = 'index') || (params[:controller] == 'front' && params[:action] = 'index') %>
              <li class="active">
            <% else %>
            	<li>
          	<% end %>
            <% if user_signed_in? %>
            	<%= link_to "Dashboard", home_index_path%>
          	<% else %>
            	<%= link_to "Home", root_path %>
          	<% end %>
        			</li>
							<% if user_signed_in? %>
								<% if params[:controller] == 'expenses' && params[:action] = 'new' && request.fullpath.split("/")[1] == 'expenses' %>
									<li class="active"><%= link_to "Post an Expense", "/expenses/new" %></li>
								<% else %>
									<li><%= link_to "Post an Expense", "/expenses/new" %></li>
								<% end %>
								<% if params[:controller] == 'expenses' && params[:action] = 'new' && request.fullpath.split("/")[1] == 'payments' %>
									<li class="active"><%= link_to "Post a Payment", "/payments/new" %></li>
								<% else %>
									<li><%= link_to "Post a payment", "/payments/new" %></li>
								<% end %>
							<% end %>
							<% if user_signed_in? %>
						  	<% if params[:controller] == 'devise/registrations' && params[:action] = 'edit' %>
						  		<li class="active"><%= link_to('Edit account', edit_user_registration_path) %></li>
					  		<% else %>
					  			<li><%= link_to('Edit account', edit_user_registration_path) %></li>
				  			<% end%>
							<% else %>
								<% if params[:controller] == 'devise/registrations' && params[:action] = 'new' %>
									<li class="active"><%= link_to "Register", "/users/sign_up" %></li>
								<% else %>
									<li><%= link_to "Register", "/users/sign_up" %></li>
								<% end %>
							<% end %>
							<% if user_signed_in? %>
								<li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
							<% else %>
								<% if params[:controller] == 'devise/sessions' && params[:action] = 'new' %>
									<li class="active"><%= link_to "Sign in", "/users/sign_in" %></li>
								<% else %>
									<li><%= link_to "Sign in", "/users/sign_in" %></li>
								<% end %>
							<% end %>
	        </ul>
	        <% if user_signed_in? %>
	        	<label class="pull-right">Welcome, <%= current_user.name %></label>
	        <% end %>
	      </div><!--/.nav-collapse -->
  	</div>
</div>
</div>
</div>